### ISSUE TITLE
Add ISO 15926-11 and or ISO 15926-12 to map?

### ISSUE THREAD

**Issue by HendrikBorgelt** [nfdi4cat/Ontology-Overview-of-NFDI4Cat#16]
While the [ISO 15926](https://standards.iso.org/iso/ts/15926/) looks promising as it is used in/with the [DEXPI Initiative](https://dexpi.org/), I am still puzzled by some of their semantic artifacts and how to combine them. A documentation i have not found yet would be nice.

Here are both Folders containing semantic artefacts:
[ISO 15926-11](https://standards.iso.org/iso/ts/15926/-11/ed-2/en/)
[ISO 15926-12](https://standards.iso.org/iso/ts/15926/-12/ed-1/en/tech/ontology/)

**Comment by AleSteB** [comment]
While the ISO is quite promising, it unfortunately has disadvantages regarding the reuse of the ontology classes. 
Thus, and because it is proprietary, the ontology is quite contrary to the "open source"-approach that this ontology overview should support.
However, in the future, this standard might be of interest, once all semantic files are open (enough) for reuse.
